# Generated by Django 5.2.8 on 2025-11-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('video_type', models.CharField(max_length=50)),
                ('num_people', models.IntegerField()),
                ('delivery_method', models.CharField(max_length=50)),
                ('gmail', models.CharField(blank=True, max_length=120, null=True)),
                ('people_data', models.TextField(blank=True, null=True)),
                ('image_paths', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
